### ISSUE TITLE
`VM.url` does not work on.... Violentmonkey

### ISSUE THREAD

**Issue by nexushoratio** [violentmonkey/vm-url#2]
Ironically, it DOES work on Tampermonkey.

Simple script:
```
// ==UserScript==
// @name Test VM.url
// @match https://github.com/*
// @noframes
// @grant window.onurlchange
// @require https://cdn.jsdelivr.net/npm/@violentmonkey/url
// ==/UserScript==

(() => {
  VM.onNavigate(() => {
    console.log('VM.onNavigate:', window.location);
  });
  if (window.onurlchange === null) {
    console.log('Using TM');
    window.addEventListener('urlchange', (info) => {
      console.log('urlchange:', info, window.location);
    });
  }
  console.log('loaded', window.location);
})();
```

In this configuration:
```
Userscript manager: Violentmonkey 2.15.0
Platform: firefox 117.0 linux x86-64
```
I get the following even after clicking to a new page:
```
 loaded Location https://github.com/violentmonkey/vm-url
```

However, in this configuration:
```
Userscript manager: Tampermonkey 4.19.0
Platform: Firefox 117.0 Linux x86-64
```
I get multiple events after changing pages (I wasn't seeing multiples on another website, so I figure this is a GH thing):
```
Using TM
loaded Location https://github.com/violentmonkey/vm-url
VM.onNavigate: Location https://github.com/violentmonkey/vm-url
urlchange: Object { url: "https://github.com/violentmonkey/vm-url" } Location https://github.com/violentmonkey/vm-url
VM.onNavigate: Location https://github.com/violentmonkey/vm-url
VM.onNavigate: Location https://github.com/violentmonkey/vm-url/issues
urlchange: Object { url: "https://github.com/violentmonkey/vm-url" } Location https://github.com/violentmonkey/vm-url/issues
urlchange: Object { url: "https://github.com/violentmonkey/vm-url/issues" } Location https://github.com/violentmonkey/vm-url/issues
VM.onNavigate: Location https://github.com/violentmonkey/vm-url/issues
urlchange: Object { url: "https://github.com/violentmonkey/vm-url/issues" } Location https://github.com/violentmonkey/vm-url/issues
```

I also tried this on LinkedIn with similar results.

**Comment by gera2ld** [comment]
Violentmonkey is blocked by GitHub CSP in Firefox. It has nothing to do with this library itself.
Tampermonkey bypasses the issue by modifying the CSP which we'd rather not.
See https://github.com/violentmonkey/violentmonkey/issues/1001

**Comment by nexushoratio** [comment]
Is it possible for the library (or calling script) to detect this and log it?

And what does it mean to be *blocked* in this case?  I have used VM to do other things on GitHub like adding elements to the page.  And I have made an extensive userscript for LinkedIn where I do all sorts of things, but only VM.url hasn't worked for me there.

I'm still new to this whole HTML/JS/CSS world and have not run into CSP issues before.

**Comment by nexushoratio** [comment]
Still researching, but I guess it boils down to this:

> Monkeypatching the `window` object may appear to work but does not actually do anything useful.

**Comment by gera2ld** [comment]
> Monkeypatching the `window` object may appear to work but does not actually do anything useful.

Exactly.

We have two worlds when injecting the script: `page` (the same as normal page scripts, restricted by CSP) and `content` (the same as the extension's scripts, not affected by CSP). Each world has its own `window`.

When blocked by the CSP, we cannot inject into `page`, so we use `content` as a fallback. As a result, any modification to `window` will not work since it's now `window` from `content` but we expect to modify the `window` from `page`.

Both worlds have access to the DOM (elements, CSS) but the JavaScript is isolated. So you can still add elements to the page. But you cannot monkeypatch or access the JavaScript objects from the `window` from `page`.

> Is it possible for the library (or calling script) to detect this and log it?

It is not a good idea for this library to do this because it doesn't have to be used in a userscript.
However, you can do it easily in your script:

```js
// Note: `injectInfo` is only available in Violentmonkey, it might be `undefined` in other script managers
if (GM_info.injectInto === 'content') {
  console.log('Injecting into `content` world. Monkeypatching will not work.');
}
```

**Comment by nexushoratio** [comment]
TYVM!
